### ISSUE TITLE
TypeError when trying to run TRAIN.py on the default dataset. 

### ISSUE THREAD

**Issue by aymanhalabya** [sagieppel/Fully-convolutional-neural-network-FCN-for-semantic-segmentation-with-pytorch#1]
I am getting a TypeError when trying to run TRAIN.py on the default dataset (materials_in_vessels) as mentioned in the instructions. 
I am using Python 3.6, pytorch 4.0
Please advise.
Thanks in advance
```Dense net encoder weights loaded
1.1981367124392763
C:\Users\halab\Anaconda2\envs\pytorch\lib\site-packages\torch\nn\functional.py:1890: UserWarning: nn.functional.upsample is deprecated. Use nn.functional.interpolate instead.
  warnings.warn("nn.functional.upsample is deprecated. Use nn.functional.interpolate instead.")
C:\Users\halab\Anaconda2\envs\pytorch\lib\site-packages\torch\nn\functional.py:1961: UserWarning: Default upsampling behavior when mode=bilinear is changed to align_corners=False since 0.4.0. Please specify align_corners=True if the old behavior is desired. See the documentation of nn.Upsample for details.
  "See the documentation of nn.Upsample for details.".format(mode))
Traceback (most recent call last):
  File "TRAIN.py", line 81, in <module>
    Prob, Lb=Net.forward(Images) # Run net inference and get prediction
  File "C:\Users\halab\Documents\GitHub\pytorchFCN\NET_FCN.py", line 92, in forward
    y = F.upsample(x, torch.from_numpy(NewSize), mode='bilinear')
  File "C:\Users\halab\Anaconda2\envs\pytorch\lib\site-packages\torch\nn\functional.py", line 1891, in upsample
    return interpolate(input, size, scale_factor, mode, align_corners)
  File "C:\Users\halab\Anaconda2\envs\pytorch\lib\site-packages\torch\nn\functional.py", line 1985, in interpolate
    return torch._C._nn.upsample_bilinear2d(input, _output_size(2), align_corners)
TypeError: upsample_bilinear2d(): argument 'output_size' (position 2) must be tuple of ints, not Tensor```

**Comment by aymanhalabya** [comment]
I figured it out, I changed line 92 in NET_FCN.py to be
```y = F.upsample(x, tuple(NewSize), mode='bilinear')```
and it worked well.
